# Default settings file for X-Road Metrics Anonymizer-module.
# Fill in your network configuration and anonymization rules.
#
# To run anonymizer for many different X-Road instances, you can create settings
# profiles. For example to have profiles DEV, TEST and PROD copy this file to
# settings_DEV.yaml, settings_TEST.yaml and settings_PROD.yaml.
# Then fill the profile specific settings to each file and use the --profile
# flag when running xroad-metrics-anonymizer. For example to run using the TEST profile:
#    xroad-metrics-anonymizer --profile TEST

xroad:
  instance: <FILL>

anonymizer:
  field-translations-file: /etc/xroad-metrics/anonymizer/field_translations.list
  field-data-file: /etc/xroad-metrics/anonymizer/field_data.yaml
  transformers:
    reduce-request-in-ts-precision: true
    force-durations-to-integer-range: true
  threads: 1

  hiding-rules:
    -   # exclude all records where client id is "foo" and service id is bar.
      - feature: 'clientMemberCode'
        regex: '^(foo)$'
      - feature: 'serviceMemberCode'
        regex: '^(bar)$'

    -   # exclude all records where service member class is not "GOV".
      - feature: 'serviceMemberClass'
        regex: '^(?!GOV$).*$'

  substitution-rules:
    - conditions:  # substitute client and service member codes with "N/A" if the client member code is "foo2"
        - feature: 'clientMemberCode'
          regex: '^foo2$'

      substitutes:
        - feature: 'clientMemberCode'
          value: 'N/A'
        - feature: 'serviceMemberCode'
          value: 'N/A'

    - conditions:  # substitute message id with 0, if service client member code is "bar2"
        - feature: 'clientMemberCode'
          regex: '^bar2$'
        - feature: 'clientMemberCode'
          regex: '^foo2$'

      substitutes:
        - feature: 'messageId'
          value: '0'

mongodb:
  host: localhost
  user: <FILL>
  password: <FILL>

postgres:
  host: localhost
  port: 5432
  user: <FILL>
  password: <FILL>
  database-name: <FILL>
  table-name: logs
  buffer-size: 10000
  readonly-users:
    - <FILL>
    - <FILL>

logger:
  name: anonymizer
  module: anonymizer

  # Possible logging levels from least to most verbose are:
  # CRITICAL, FATAL, ERROR, WARNING, INFO, DEBUG
  level: INFO

  # Logs and heartbeat files are stored under these paths.
  # Also configure external log rotation and app monitoring accordingly.
  log-path: /var/log/xroad-metrics/anonymizer/logs
  heartbeat-path: /var/log/xroad-metrics/anonymizer/heartbeat
