xroad:
  instance: <FILL>

  # X-Road descriptor file that lists all subsystems available.
  # Optionally the file may include localized subsystem names and maintainer e-mail addresses.
  descriptor-path: /etc/xroad-metrics/reports/xroad-descriptor.json

mongodb:
  host: localhost
  user: <FILL>
  password: <FILL>

logger:
  name: reports
  module: reports

  # Possible logging levels from least to most verbose are:
  # CRITICAL, FATAL, ERROR, WARNING, INFO, DEBUG
  level: INFO

  # Logs and heartbeat files are stored under these paths.
  # Also configure external log rotation and app monitoring accordingly.
  log-path: /var/log/xroad-metrics/reports/logs
  heartbeat-path: /var/log/xroad-metrics/reports/heartbeat

reports:
  report-path: /var/lib/xroad-metrics/reports
  translation-path: /etc/xroad-metrics/reports/lang
  html-template:
    dir: /etc/xroad-metrics/reports/template
    file: pdf_report_template.html
  css-paths:
    - '/etc/xroad-metrics/reports/template/pdf_report_style.css'
  image-path: /etc/xroad-metrics/reports/template/header_images
  email:
    sender: <FILL>  # e-mail address shown in sender field of notifications
    smtp:
      host: <FILL>
      user: <FILL>
      password: ""  # only needed if encryption is selected
      port: 25
      encryption: None  # possible values: None, TLS, STARTTLS
    message: >
      Dear {EMAIL_NAME},


      There's a new X-Road Metrics report available for an X-Road subsystem where
      you are listed as a contact person.


      Report name: {REPORT_NAME}

      X-Road subsystem: {X_ROAD_INSTANCE}:{MEMBER_CLASS}:{MEMBER_CODE}:{SUBSYSTEM_CODE}

      Report time period: from {START_DATE} to {END_DATE}


      Best regards,

      X-Road Metrics Administration

    subject: "X-Road Metrics report for {X_ROAD_INSTANCE}:{MEMBER_CLASS}:{MEMBER_CODE}:{SUBSYSTEM_CODE}"
