---
excludes:
  paths:
  - pattern: "**/test_requirements.txt"
    reason: "TEST_OF"
    comment: "Requirements for testing."
  - pattern: "3RD-PARTY-NOTICES.txt"
    reason: "DOCUMENTATION_OF"
    comment: "3rd party notices."

  scopes:
  - pattern: "checkstyle"
    reason: "BUILD_DEPENDENCY_OF"
    comment: "Packages for code styling checks (testing) only."

  - pattern: "devDependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "jacocoAgent"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "jacocoAnt"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "test.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."

  - pattern: "annotationProcessor"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileClasspath"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileOnly"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."
