xroad:
  instance: <FILL>

networking:
  interval: 5
  buffer: 10
  metaservices:
    - "getWsdl"
    - "listMethods"
    - "allowedMethods"
    - "getSecurityServerMetrics"
    - "getSecurityServerOperationalData"
    - "getSecurityServerHealthData"
  xroad-descriptor-file: /etc/opmon/networking/xroad-descriptor.json

postgres:
  host: localhost
  port: 5432
  username: <FILL>
  password: <FILL>

logger:
  log-path: /var/log/opmon/networking/logs
  heartbeat-path: /var/log/opmon/networking/heartbeat
