xroad:
  instance: <FILL>

opendata:
  delay-days: 10
  preview-limit: 10
  field-data-path: /etc/xroad-metrics/opendata/field_data.yaml
  maintenance-mode: false
  disclaimer: "<!--insert your custom HTML disclaimer here-->"
  header: "<!--insert your custom HTML header here-->"
  footer: "<!--insert your custom HTML footer here-->"

postgres:
  host: localhost
  port: 5432
  user: <FILL>
  password: <FILL>
  database-name: <FILL>
  table-name: logs

logger:
  name: opendata
  module: opendata

  # Possible logging levels from least to most verbose are:
  # CRITICAL, FATAL, ERROR, WARNING, INFO, DEBUG
  level: INFO

  # Logs and heartbeat files are stored under these paths.
  # Also configure external log rotation and app monitoring accordingly.
  log-path: /var/log/xroad-metrics/opendata/logs
  heartbeat-path: /var/log/xroad-metrics/opendata/heartbeat

django:
  secret-key: <FILL>
  allowed-hosts:
    - '*'
